@include('universal.header.header_normal')
@include('account.resetPassword.source.JsAndCss')
@include('universal.top.layoutTop')
@include('account.resetPassword.page.indexInc')
@include('universal.footer.bottom')