@include('universal.header.header_normal')
@include('account.register.source.JsAndCss')
@include('universal.top.layoutTop')
@include('account.register.page.indexInc')
@include('universal.footer.bottom')