@include('universal.header.header_normal')
@include('static.donate.source.Css')
@include('universal.top.layoutTop',["topLayoutId"=>'layout-top-nobackground',"topNavValueText"=>""])
@include('hook.page.indexInc')
@include('universal.footer.bottom')
