@include('universal.header.header_normal')
@include('auth.add.source.JsAndCss')
@include('universal.top.layoutTop')
@include('auth.add.page.indexInc')
@include('auth.add.source.JsPaste')
@include('universal.footer.bottom')