@include('universal.header.header_normal',["topNavValueText"=> "首页"])
@include('auth.get.source.JsAndCss')
@include('universal.top.layoutTop')
@include('auth.get.page.indexInc')
@include('universal.footer.bottom')